custom:
  jwt:
    secret-key: "abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890123"
  admin:
    admin-code: "ADMINCODE"

spring:
  mail:
    verification:
      sender: admin@cafe.com
    host: smtp.gmail.com
    port: 587
    username: "jmy8876@gmail.com"
    password: "jgwi wcey hhpc uors"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000